on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy blog to hydrogen
    if: github.ref == 'refs/heads/main'
    env:
      MACHINE: hydrogen
    steps:
      - name: Setup Go 1.17
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Setup Tailscale
        id: tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.tskey-auth-konnJd2CNTRL-xvHpXhz2AhKHwhYBbVumcK5ULeXbaeiT1 }}
